Save md file
tfachmann/MdCollab pull request #29
Opened 2020-07-06 12:54 UTC by SI3G

2020-07-06 21:19 UTC, NelDav requested changes

2020-07-06 21:19 UTC, NelDav commented on site/index.js
> +function get_contents() {
I would change this to `get_md_content()`. Otherwise we would run into trouble during the implementation of html and pdf export.

2020-07-06 21:19 UTC, NelDav commented on site/index.js
> +    var file = new Blob([contents], {type: 'text/plain'});
In the functions above `let` ist used instead of `var`. There is no difference between `let` and `var` in this situation. I think you should also use `let` because of consitency.

2020-07-06 21:19 UTC, NelDav commented on site/index.js
> +    }
I think you are right. That is the only native way to download the text. But I found the [FileSaver.js](https://github.com/eligrey/FileSaver.js/) module. It is much easier if you use it.

I will create a PR into this branch to show you how the FileSaver module works.

2020-07-06 21:28 UTC, NelDav commented
As promised here is the PR which implements the FileSaver.js module: #31

2020-07-08 06:55 UTC, SI3G commented
Your changes have been pulled into the branch save-md-file. Please resolve the conversation and merge this branch with branch master.

2020-07-08 12:44 UTC, NelDav approved these changes
I think this PR is ready for merge now.

2020-07-08 12:53 UTC, merged